### ISSUE TITLE
no need of so much icons in nav change needed

### ISSUE THREAD

**Issue by ragineedarade** [ayush-that/FinVeda#973]
we need to remove so much icon its not looking good  can you  please  assign this me under gssoc-ext level.

**Comment by Devanshu1603** [comment]
can you assign this me under gssoc-ext level. will be happy to contribute

**Comment by Shalinis19137** [comment]
![Screenshot 2024-10-02 153753](https://github.com/user-attachments/assets/07dab63d-e701-4b87-9b28-2d337f17a199)
1. at this part of "Headline" their is no need of QUIZ section (because it work as FAQ section) and FAQ section made at end of the page
![Screenshot 2024-10-02 153850](https://github.com/user-attachments/assets/ba3e6825-57d8-4e6d-85b7-a1e5e5b715d1)
2. At this part we directly attach links of linkedin accounts of student

**Comment by Shalinis19137** [comment]
Please Assign this issue to me

**Comment by ragineedarade** [comment]
can you give lable of gssoc levels

**Comment by deepeshmlgupta** [comment]
no, update since last week so closing
